#ifndef _UTILITIES_ASCII_KEY_H_
#define _UTILITIES_ASCII_KEY_H_

#define ASCII_KEY_NULL	0
#define ASCII_KEY_SOH	1
#define ASCII_KEY_STX	2
#define ASCII_KEY_ETX	3
#define ASCII_KEY_EOT	4
#define ASCII_KEY_ENQ	5
#define ASCII_KEY_ACK	6
#define ASCII_KEY_BEL	7
#define ASCII_KEY_BS    8
#define ASCII_KEY_HT	9
#define ASCII_KEY_LF	10
#define ASCII_KEY_VT   	11
#define ASCII_KEY_FF   	12
#define ASCII_KEY_CR	13
#define ASCII_KEY_SO	14
#define ASCII_KEY_SI	15
#define ASCII_KEY_DLE	16
#define ASCII_KEY_DC1	17
#define ASCII_KEY_DC2	18
#define ASCII_KEY_DC3	19
#define ASCII_KEY_DC4	20
#define ASCII_KEY_NAK	21
#define ASCII_KEY_SYN	22
#define ASCII_KEY_ETB	23
#define ASCII_KEY_CAN	24
#define ASCII_KEY_EM	25
#define ASCII_KEY_SUB	26
#define ASCII_KEY_ESC	27
#define ASCII_KEY_FS	28
#define ASCII_KEY_GS	29
#define ASCII_KEY_RS	30
#define ASCII_KEY_US	31
#define ASCII_KEY_SPACE	32
#define ASCII_KEY_!		33
#define ASCII_KEY_"		34
#define ASCII_KEY_#		35
#define ASCII_KEY_$		36
#define ASCII_KEY_%		37
#define ASCII_KEY_&		38
#define ASCII_KEY_'		39
#define ASCII_KEY_(		40
#define ASCII_KEY_)		41
#define ASCII_KEY_*		42
#define ASCII_KEY_+		43
#define ASCII_KEY_,		44
#define ASCII_KEY_-		45
#define ASCII_KEY_.		46
#define ASCII_KEY_/		47
#define ASCII_KEY_0		48
#define ASCII_KEY_1		49
#define ASCII_KEY_2		50
#define ASCII_KEY_3		51
#define ASCII_KEY_4		52
#define ASCII_KEY_5		53
#define ASCII_KEY_6		54
#define ASCII_KEY_7		55
#define ASCII_KEY_8		56
#define ASCII_KEY_9		57
#define ASCII_KEY_:		58
#define ASCII_KEY_;		59
#define ASCII_KEY_<		60
#define ASCII_KEY_=		61
#define ASCII_KEY_>		62
#define ASCII_KEY_?		63
#define ASCII_KEY_@		64
#define ASCII_KEY_A		65
#define ASCII_KEY_B		66
#define ASCII_KEY_C		67
#define ASCII_KEY_D		68
#define ASCII_KEY_E		69
#define ASCII_KEY_F		70
#define ASCII_KEY_G		71
#define ASCII_KEY_H		72
#define ASCII_KEY_I		73
#define ASCII_KEY_J		74
#define ASCII_KEY_K		75
#define ASCII_KEY_L		76
#define ASCII_KEY_M		77
#define ASCII_KEY_N		78
#define ASCII_KEY_O		79
#define ASCII_KEY_P		80
#define ASCII_KEY_Q		81
#define ASCII_KEY_R		82
#define ASCII_KEY_S		83
#define ASCII_KEY_T		84
#define ASCII_KEY_U		85
#define ASCII_KEY_V		86
#define ASCII_KEY_W		87
#define ASCII_KEY_X		88
#define ASCII_KEY_Y		89
#define ASCII_KEY_Z		90
#define ASCII_KEY_[		91
#define ASCII_KEY_\		92
#define ASCII_KEY_]		93
#define ASCII_KEY_^		94
#define ASCII_KEY__		95
#define ASCII_KEY_`		96
#define ASCII_KEY_a		97
#define ASCII_KEY_b		98
#define ASCII_KEY_c		99
#define ASCII_KEY_d		100
#define ASCII_KEY_e		101
#define ASCII_KEY_f		102
#define ASCII_KEY_g		103
#define ASCII_KEY_h		104
#define ASCII_KEY_i		105
#define ASCII_KEY_j		106
#define ASCII_KEY_k		107
#define ASCII_KEY_l		108
#define ASCII_KEY_m		109
#define ASCII_KEY_n		110
#define ASCII_KEY_o		111
#define ASCII_KEY_p		112
#define ASCII_KEY_q		113
#define ASCII_KEY_r		114
#define ASCII_KEY_s		115
#define ASCII_KEY_t		116
#define ASCII_KEY_u		117
#define ASCII_KEY_v		118
#define ASCII_KEY_w		119
#define ASCII_KEY_x		120
#define ASCII_KEY_y		121
#define ASCII_KEY_z		122
#define ASCII_KEY_{		123
#define ASCII_KEY_|		124
#define ASCII_KEY_}		125
#define ASCII_KEY_~		126
#define ASCII_KEY_DEL	127

#endif

